source("algorithm/generate_candidate_cuts.R")
source("algorithm/refine_candidate_cuts.R")
source("algorithm/get_LM.R")
source("algorithm/utils.R")
source("algorithm/search_oned.R")
source("algorithm/initialize_bin.R")
source("algorithm/search_md.R")
source("algorithm/get_which_dim.R")
source("algorithm/print_bins.R")

source("algorithm/merging.R")
source("algorithm/visualization/produce_short_line_segs.R")
source("algorithm/visualization/visual_2d_MDLhist.R")
source("algorithm/visualization/visualize_twod_hist.R")
source("algorithm/visualization/whether_neighbour.R")
